services:
  consul:
    image: consul:1.15
    ports:
      - "18500:8500"
    command: agent -server -bind=0.0.0.0 -client=0.0.0.0 -bootstrap-expect=1 -ui

  service1-1:
    build: ./Service1
    hostname: service1-1
    ports:
      - "19990:9990"
    depends_on:
      - consul

  service1-2:
    build: ./Service1
    hostname: service1-2
    ports:
      - "19991:9990"
    depends_on:
      - consul

  service2-1:
    build: ./Service2
    hostname: service2-1
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - JAX_RS_SERVICE_BASEURL=https://haproxy:8443/api
      - SERVER_PORT=8083
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_KEY_STORE=file:/app/keystore.p12
      - SERVER_SSL_KEY_STORE_PASSWORD=password
      - SERVER_SSL_KEY_STORE_TYPE=PKCS12
      - SPRING_CLOUD_CONSUL_DISCOVERY_SCHEME=https
      - SPRING_CLOUD_CONSUL_DISCOVERY_HEALTH_CHECK_TLS_SKIP_VERIFY=true
      - JAVA_TOOL_OPTIONS=-Djavax.net.ssl.trustStore=/app/keystore.p12 -Djavax.net.ssl.trustStorePassword=password -Djavax.net.ssl.trustStoreType=PKCS12
    depends_on:
      - consul
      - service1-1

  service2-2:
    build: ./Service2
    hostname: service2-2
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - JAX_RS_SERVICE_BASEURL=https://haproxy:8443/api
      - SERVER_PORT=8083
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_KEY_STORE=file:/app/keystore.p12
      - SERVER_SSL_KEY_STORE_PASSWORD=password
      - SERVER_SSL_KEY_STORE_TYPE=PKCS12
      - SPRING_CLOUD_CONSUL_DISCOVERY_SCHEME=https
      - SPRING_CLOUD_CONSUL_DISCOVERY_HEALTH_CHECK_TLS_SKIP_VERIFY=true
      - JAVA_TOOL_OPTIONS=-Djavax.net.ssl.trustStore=/app/keystore.p12 -Djavax.net.ssl.trustStorePassword=password -Djavax.net.ssl.trustStoreType=PKCS12
    depends_on:
      - consul

  haproxy:
    image: haproxy:2.8
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./certs/haproxy.pem:/usr/local/etc/haproxy/haproxy.pem:ro
    ports:
      - "18443:8443"
      - "18444:8444"
      - "1937:1936"
    depends_on:
      - service1-1
      - service1-2
      - service2-1
      - service2-2


